export const FIELD_CN: Record<string, { label: string; doc: string }> = {
  visibility: { label: '可见性', doc: 'visible 显示，none 隐藏。不影响图层顺序。' },

  'fill-sort-key': { label: '填充排序', doc: '数值越大越靠上绘制。' },
  'fill-antialias': { label: '抗锯齿', doc: '边缘是否平滑。' },
  'fill-opacity': { label: '填充透明度', doc: '0 全透明，1 不透明。可开过渡动画。' },
  'fill-color': { label: '填充颜色', doc: '面颜色。选「字段」可按属性上色。' },
  'fill-outline-color': { label: '轮廓颜色', doc: '仅抗锯齿开启时生效。' },
  'fill-translate': { label: '填充偏移', doc: '像素偏移 [x, y]。' },
  'fill-translate-anchor': { label: '偏移参照', doc: 'map 随地图转，viewport 相对屏幕。' },
  'fill-pattern': { label: '填充图案', doc: '填精灵图里的图标名。' },
  'fill-emissive-strength': { label: '自发光', doc: '夜间/灯光下自身发亮强度。' },
  'fill-z-offset': { label: '高度偏移', doc: '沿 z 轴抬高，单位米。' },

  'line-cap': { label: '线端', doc: 'butt 平切，round 圆头，square 方头。' },
  'line-join': { label: '线拐角', doc: 'bevel / round / miter。' },
  'line-miter-limit': { label: '尖角限制', doc: '超过后改用 bevel。' },
  'line-round-limit': { label: '圆角限制', doc: '控制 round 拐角的最小角度。' },
  'line-sort-key': { label: '线排序', doc: '数值越大越靠上。' },
  'line-z-offset': { label: '线高度偏移', doc: '沿高程抬起，适合压盖地形。' },
  'line-elevation-reference': { label: '高程参照', doc: '相对海平面或地面。' },
  'line-cross-slope': { label: '横坡', doc: '线贴地时的横向倾斜。' },
  'line-opacity': { label: '线透明度', doc: '可开过渡做淡入淡出。' },
  'line-color': { label: '线颜色', doc: '选「字段」可按道路等级上色。' },
  'line-translate': { label: '线偏移', doc: '像素 [x, y]。' },
  'line-translate-anchor': { label: '线偏移参照', doc: 'map 或 viewport。' },
  'line-width': { label: '线宽', doc: '选「缩放动画」可随级别变粗。' },
  'line-gap-width': { label: '中空宽度', doc: '双线中间的空隙。' },
  'line-offset': { label: '线侧移', doc: '正负值向左右偏移，单位像素。' },
  'line-blur': { label: '线模糊', doc: '边缘虚化像素。' },
  'line-dasharray': { label: '虚线', doc: '如 [2, 4] 表示画 2 空 4。' },
  'line-pattern': { label: '线图案', doc: '精灵图名称，沿线路重复。' },
  'line-gradient': { label: '线渐变', doc: '需 lineMetrics。表达式控制沿线颜色。' },
  'line-emissive-strength': { label: '线自发光', doc: '灯光下发亮强度。' },
  'line-occlusion-opacity': { label: '遮挡透明度', doc: '被 3D 挡住时的透明度。' },
  'line-border-width': { label: '线边框宽', doc: '线外侧描边宽度。' },
  'line-border-color': { label: '线边框色', doc: '描边颜色。' },

  'symbol-placement': { label: '符号放置', doc: 'point 点，line 沿线，line-center 线中点。' },
  'symbol-spacing': { label: '符号间距', doc: '沿线重复的间距，像素。' },
  'symbol-avoid-edges': { label: '避开瓦片边', doc: '减少瓦片接缝处切断注记。' },
  'symbol-sort-key': { label: '符号排序', doc: '越小越优先显示。' },
  'symbol-z-elevate': { label: '贴屋顶', doc: '开启后注记抬到建筑屋顶。' },
  'icon-allow-overlap': { label: '图标允许重叠', doc: 'true 则不避让。' },
  'icon-ignore-placement': { label: '图标不占位', doc: '不挡住其他符号。' },
  'icon-optional': { label: '图标可省略', doc: '空间不够时只留文字。' },
  'icon-rotation-alignment': { label: '图标旋转对齐', doc: 'map 随地图，viewport 朝屏幕。' },
  'icon-size': { label: '图标大小', doc: '1 为原尺寸。可随缩放变化。' },
  'icon-text-fit': { label: '图标适配文字', doc: '按文字宽高拉伸图标。' },
  'icon-image': { label: '图标', doc: '填 sprite 里的名字。' },
  'icon-rotate': { label: '图标旋转', doc: '度数。' },
  'icon-padding': { label: '图标边距', doc: '碰撞检测内边距。' },
  'icon-keep-upright': { label: '图标保持正立', doc: '沿线时尽量不倒置。' },
  'icon-offset': { label: '图标偏移', doc: '[x, y]，单位为 icon-size 倍数。' },
  'icon-anchor': { label: '图标锚点', doc: '图标哪一点对准坐标。' },
  'icon-pitch-alignment': { label: '图标俯仰对齐', doc: '倾斜地图时是否立起来。' },
  'text-pitch-alignment': { label: '文字俯仰对齐', doc: '倾斜时文字是否立起。' },
  'text-rotation-alignment': { label: '文字旋转对齐', doc: 'map / viewport / auto。' },
  'text-field': { label: '文字内容', doc: '选「字段」填 name 等属性；也可用 ["get","name"]。' },
  'text-font': { label: '字体', doc: '须与服务器 fonts 目录名一致，如 Open Sans Regular。' },
  'text-size': { label: '字号', doc: '选「缩放动画」可随级别变大。' },
  'text-max-width': { label: '最大行宽', doc: '超过则换行，单位 em。' },
  'text-line-height': { label: '行高', doc: '倍数。' },
  'text-letter-spacing': { label: '字距', doc: '单位 em。' },
  'text-justify': { label: '对齐', doc: '多行文字左右对齐方式。' },
  'text-radial-offset': { label: '径向偏移', doc: '相对锚点向外推。' },
  'text-variable-anchor': { label: '可变锚点', doc: '避让时尝试的锚点列表。' },
  'text-anchor': { label: '文字锚点', doc: '文字哪一点对准坐标。' },
  'text-max-angle': { label: '最大转角', doc: '沿线文字允许的最大折角。' },
  'text-writing-mode': { label: '书写方向', doc: 'horizontal / vertical。' },
  'text-rotate': { label: '文字旋转', doc: '度数。' },
  'text-padding': { label: '文字边距', doc: '碰撞检测边距。' },
  'text-keep-upright': { label: '文字保持正立', doc: '沿线时避免倒置。' },
  'text-transform': { label: '大小写', doc: 'none / uppercase / lowercase。' },
  'text-offset': { label: '文字偏移', doc: '[x, y]，单位 em。' },
  'text-allow-overlap': { label: '文字允许重叠', doc: 'true 则强制画出。' },
  'text-ignore-placement': { label: '文字不占位', doc: '不挡住其他符号。' },
  'text-optional': { label: '文字可省略', doc: '空间不够时只留图标。' },
  'icon-opacity': { label: '图标透明度', doc: '可开过渡做淡入。' },
  'icon-color': { label: '图标颜色', doc: 'SDF 图标才生效。' },
  'icon-halo-color': { label: '图标光晕色', doc: '描边色。' },
  'icon-halo-width': { label: '图标光晕宽', doc: '描边宽度。' },
  'icon-halo-blur': { label: '图标光晕模糊', doc: '描边虚化。' },
  'icon-translate': { label: '图标平移', doc: '像素 [x, y]。' },
  'icon-translate-anchor': { label: '图标平移参照', doc: 'map 或 viewport。' },
  'icon-emissive-strength': { label: '图标自发光', doc: '灯光下发亮。' },
  'text-opacity': { label: '文字透明度', doc: '可开过渡。' },
  'text-color': { label: '文字颜色', doc: '选「字段」可分类着色。' },
  'text-halo-color': { label: '文字描边色', doc: '衬底，提高对比度。' },
  'text-halo-width': { label: '文字描边宽', doc: '建议 0.5～1.5。' },
  'text-halo-blur': { label: '文字描边模糊', doc: '软化描边。' },
  'text-translate': { label: '文字平移', doc: '像素 [x, y]。' },
  'text-translate-anchor': { label: '文字平移参照', doc: 'map 或 viewport。' },
  'text-emissive-strength': { label: '文字自发光', doc: '灯光下发亮。' },

  'circle-sort-key': { label: '圆点排序', doc: '越大越靠上。' },
  'circle-elevation-reference': { label: '圆点高程参照', doc: '相对海平面或地面。' },
  'circle-radius': { label: '半径', doc: '选「缩放动画」可随级别变大。' },
  'circle-color': { label: '圆点颜色', doc: '选「字段」按属性上色。' },
  'circle-blur': { label: '圆点模糊', doc: '0～1，越大越虚。' },
  'circle-opacity': { label: '圆点透明度', doc: '可开过渡。' },
  'circle-translate': { label: '圆点偏移', doc: '像素 [x, y]。' },
  'circle-translate-anchor': { label: '圆点偏移参照', doc: 'map 或 viewport。' },
  'circle-pitch-scale': { label: '倾斜缩放', doc: '倾斜时圆是否透视变大。' },
  'circle-pitch-alignment': { label: '倾斜对齐', doc: '贴地还是朝屏幕。' },
  'circle-stroke-width': { label: '描边宽', doc: '圆边框宽度。' },
  'circle-stroke-color': { label: '描边色', doc: '圆边框颜色。' },
  'circle-stroke-opacity': { label: '描边透明度', doc: '边框透明度。' },
  'circle-emissive-strength': { label: '圆点自发光', doc: '灯光下发亮。' },

  'heatmap-radius': { label: '热力半径', doc: '影响范围，像素。' },
  'heatmap-weight': { label: '热力权重', doc: '每个点的贡献，可绑字段。' },
  'heatmap-intensity': { label: '热力强度', doc: '整体放大系数。' },
  'heatmap-color': { label: '热力配色', doc: '按密度插值颜色。' },
  'heatmap-opacity': { label: '热力透明度', doc: '可开过渡。' },

  'fill-extrusion-opacity': { label: '拉伸透明度', doc: '整层透明度，不能数据驱动。' },
  'fill-extrusion-color': { label: '拉伸颜色', doc: '墙体颜色。选「字段」按楼栋上色。' },
  'fill-extrusion-translate': { label: '拉伸偏移', doc: '像素 [x, y]。' },
  'fill-extrusion-translate-anchor': { label: '拉伸偏移参照', doc: 'map 或 viewport。' },
  'fill-extrusion-pattern': { label: '拉伸贴图', doc: '精灵图名称。' },
  'fill-extrusion-height': {
    label: '拉伸高度',
    doc: '建筑高度（米）。选「字段」填 height；选「缩放动画」可从 0 升到真实高度，这就是常见的建筑升起。',
  },
  'fill-extrusion-base': {
    label: '拉伸底高',
    doc: '底部离地高度。多层建筑用 min_height。升起动画时与高度用同一组缩放停靠。',
  },
  'fill-extrusion-height-alignment': { label: '高度对齐', doc: 'terrain 贴地形，flat 水平。' },
  'fill-extrusion-base-alignment': { label: '底面对齐', doc: 'terrain 或 flat。' },
  'fill-extrusion-vertical-gradient': { label: '竖向渐变', doc: '墙面上下明暗，更像真实建筑。' },
  'fill-extrusion-vertical-scale': {
    label: '高度倍率',
    doc: '整体乘在高度上。从 0 改到 1 并配 transition，可做「长出来」的动画（常量之间才有过渡）。',
  },
  'fill-extrusion-rounded-roof': { label: '圆屋顶', doc: '屋顶是否圆滑。' },
  'fill-extrusion-edge-radius': { label: '墙角圆角', doc: '单位米，Mapbox 3.0 圆角建筑。' },
  'fill-extrusion-line-width': { label: '墙厚', doc: '拉伸轮廓线宽。' },
  'fill-extrusion-ambient-occlusion-intensity': { label: '环境光遮蔽强度', doc: '墙根阴影，0.3 左右较自然。' },
  'fill-extrusion-ambient-occlusion-radius': { label: '遮蔽半径', doc: '旧版灯光用，约一层楼高 3 米。' },
  'fill-extrusion-ambient-occlusion-wall-radius': { label: '墙面遮蔽半径', doc: '3D 灯光下的墙面凹影范围。' },
  'fill-extrusion-ambient-occlusion-ground-radius': { label: '地面遮蔽半径', doc: '建筑在地面投下的暗区范围（米）。' },
  'fill-extrusion-ambient-occlusion-ground-attenuation': { label: '地面遮蔽衰减', doc: '越小越实，越大越柔。' },
  'fill-extrusion-ambient-occlusion-ground-intensity': { label: '地面遮蔽强度', doc: '地面暗区强弱。' },
  'fill-extrusion-flood-light-color': { label: '泛光颜色', doc: '墙脚洗墙灯颜色。' },
  'fill-extrusion-flood-light-intensity': { label: '泛光强度', doc: '0 关闭。可配 transition 做亮灯动画。' },
  'fill-extrusion-flood-light-wall-radius': { label: '墙面泛光半径', doc: '灯光沿墙爬升距离（米）。' },
  'fill-extrusion-flood-light-ground-radius': { label: '地面泛光半径', doc: '地面被照亮的范围（米）。' },
  'fill-extrusion-flood-light-ground-attenuation': { label: '地面泛光衰减', doc: '光斑边缘软硬。' },
  'fill-extrusion-cutoff-fade-range': { label: '远景消隐', doc: '倾斜视角远处建筑逐渐缩小消失，0 关闭。' },
  'fill-extrusion-cast-shadows': { label: '投射阴影', doc: '需要样式里配置 3D 灯光。' },
  'fill-extrusion-emissive-strength': { label: '墙体自发光', doc: '夜间窗户发光一类效果。' },

  'building-height': {
    label: '建筑高度',
    doc: 'procedural 建筑高度。选「字段」填 height；选「缩放动画」15 级为 0、16 级为真实高度，可做升起。',
  },
  'building-base': { label: '建筑底高', doc: '底部高度，常用 min_height。' },
  'building-roof-shape': { label: '屋顶形状', doc: 'flat 平顶，gabled 双坡，hipped 四坡等。' },
  'building-facade': { label: '生成立面', doc: '开启后画窗格立面。' },
  'building-facade-floors': { label: '立面层数', doc: '窗格分层数量。' },
  'building-facade-unit-width': { label: '立面开间', doc: '每跨窗宽度。' },
  'building-facade-window': { label: '窗户比例', doc: '窗在立面上的宽高比例。' },
  'building-flood-light-wall-radius': { label: '墙面泛光半径', doc: '洗墙范围（米）。' },
  'building-flood-light-ground-radius': { label: '地面泛光半径', doc: '地面光斑（米）。' },
  'building-flip-roof-orientation': { label: '翻转屋顶朝向', doc: '调坡屋顶方向。' },
  'building-opacity': { label: '建筑透明度', doc: '整栋透明度。' },
  'building-color': { label: '建筑颜色', doc: '墙体颜色，可绑字段。' },
  'building-vertical-scale': {
    label: '高度倍率',
    doc: '0～1 缩放整栋高度。配「过渡」从 0 到 1，就是长高动画（两个常量之间才会平滑过渡）。',
  },
  'building-cast-shadows': { label: '投射阴影', doc: '需 3D 灯光。' },
  'building-ambient-occlusion-intensity': { label: '环境光遮蔽', doc: '墙根阴影强度，建议 0.3。' },
  'building-ambient-occlusion-ground-intensity': { label: '地面遮蔽强度', doc: '地面暗区。' },
  'building-ambient-occlusion-ground-radius': { label: '地面遮蔽半径', doc: '单位米。' },
  'building-ambient-occlusion-ground-attenuation': { label: '地面遮蔽衰减', doc: '边缘软硬。' },
  'building-emissive-strength': { label: '建筑自发光', doc: '夜间发光。' },
  'building-facade-emissive-chance': { label: '窗户亮灯概率', doc: '0～1，随机点亮部分窗户。' },
  'building-cutoff-fade-range': { label: '远景消隐', doc: '远处建筑淡出，0 关闭。' },
  'building-front-cutoff': { label: '近处裁切', doc: '相机近处切除建筑，避免挡视线。' },
  'building-flood-light-color': { label: '泛光颜色', doc: '洗墙灯颜色。' },
  'building-flood-light-intensity': { label: '泛光强度', doc: '配过渡可做亮灯。' },
  'building-flood-light-ground-attenuation': { label: '地面泛光衰减', doc: '光斑边缘。' },

  'raster-opacity': { label: '栅格透明度', doc: '影像透明度。' },
  'raster-hue-rotate': { label: '色相旋转', doc: '度数。' },
  'raster-brightness-min': { label: '最小亮度', doc: '0～1。' },
  'raster-brightness-max': { label: '最大亮度', doc: '0～1。' },
  'raster-saturation': { label: '饱和度', doc: '-1～1。' },
  'raster-contrast': { label: '对比度', doc: '-1～1。' },
  'raster-resampling': { label: '重采样', doc: 'linear 平滑，nearest 像素风。' },
  'raster-fade-duration': { label: '瓦片淡入', doc: '新瓦片出现的毫秒数。' },
  'raster-emissive-strength': { label: '栅格自发光', doc: '灯光下发亮。' },

  'hillshade-illumination-direction': { label: '光照方向', doc: '0～359，335 为西北光。' },
  'hillshade-illumination-anchor': { label: '光照参照', doc: 'map 随旋转，viewport 固定屏幕。' },
  'hillshade-exaggeration': { label: '地形夸张', doc: '阴影强弱。' },
  'hillshade-shadow-color': { label: '阴影色', doc: '背光面颜色。' },
  'hillshade-highlight-color': { label: '高光色', doc: '迎光面颜色。' },
  'hillshade-accent-color': { label: '强调色', doc: '坡折处颜色。' },
  'hillshade-emissive-strength': { label: '山影自发光', doc: '灯光下发亮。' },

  'background-color': { label: '背景色', doc: '无数据区域底色。' },
  'background-pattern': { label: '背景图案', doc: '精灵图名称。' },
  'background-opacity': { label: '背景透明度', doc: '可开过渡。' },
  'background-emissive-strength': { label: '背景自发光', doc: '灯光下发亮。' },
  'background-pitch-alignment': { label: '背景俯仰对齐', doc: 'map 或 viewport。' },

  'sky-type': { label: '天空类型', doc: 'atmosphere 大气，gradient 渐变。' },
  'sky-atmosphere-sun': { label: '太阳位置', doc: '[方位角, 高度角]。' },
  'sky-atmosphere-sun-intensity': { label: '太阳强度', doc: '0～100。' },
  'sky-gradient': { label: '天空渐变', doc: '自定义颜色插值。' },
  'sky-atmosphere-halo-color': { label: '日晕颜色', doc: '太阳周围光晕。' },
  'sky-atmosphere-color': { label: '大气颜色', doc: '天空主色。' },
  'sky-opacity': { label: '天空透明度', doc: '可开过渡。' },

  'clip-layer-types': { label: '裁剪图层类型', doc: '要裁掉的类型列表。' },
  'clip-layer-scope': { label: '裁剪范围', doc: '限定哪些图层被裁。' },

  'raster-particle-array-band': { label: '粒子波段', doc: '使用的栅格波段。' },
  'raster-particle-count': { label: '粒子数量', doc: '越多越密、越耗性能。' },
  'raster-particle-color': { label: '粒子颜色', doc: '按速度上色。' },
  'raster-particle-max-speed': { label: '最大速度', doc: '颜色映射上限。' },
  'raster-particle-speed-factor': { label: '速度系数', doc: '运动快慢。' },
  'raster-particle-fade-opacity-factor': { label: '拖尾衰减', doc: '越接近 1 拖尾越长。' },
  'raster-particle-reset-rate-factor': { label: '重生速率', doc: '粒子重新投放的快慢。' },
  'raster-particle-elevation-reference': { label: '粒子高程', doc: 'sea 或 ground。' },

  'model-id': { label: '模型 ID', doc: '样式 models 里的模型名。' },
  'model-opacity': { label: '模型透明度', doc: '可开过渡。' },
  'model-rotation': { label: '模型旋转', doc: '[x, y, z] 度数。' },
  'model-scale': { label: '模型缩放', doc: '[x, y, z]。' },
  'model-translation': { label: '模型平移', doc: '[x, y, z] 米。' },
  'model-color': { label: '模型颜色', doc: '与贴图混合。' },
  'model-color-mix-intensity': { label: '颜色混合', doc: '0 用贴图，1 纯色。' },
  'model-type': { label: '模型类型', doc: 'common-3d 或 location-indicator。' },
  'model-cast-shadows': { label: '模型阴影', doc: '是否投影。' },
  'model-emissive-strength': { label: '模型自发光', doc: '夜间发光。' },
  'model-roughness': { label: '粗糙度', doc: '0 镜面，1 哑光。' },
  'model-height-based-emissive-strength-multiplier': { label: '按高度发光', doc: '随高度变化的发光倍数。' },
  'model-cutoff-fade-range': { label: '模型远景消隐', doc: '远处淡出。' },
}

export function fieldLabel(name: string): string {
  if (FIELD_CN[name]) return FIELD_CN[name].label
  if (name.endsWith('-transition')) {
    const base = name.slice(0, -'-transition'.length)
    return `${fieldLabel(base)} · 过渡`
  }
  return name
}

export function fieldDoc(name: string): string {
  if (FIELD_CN[name]) return FIELD_CN[name].doc
  if (name.endsWith('-transition')) {
    const base = name.slice(0, -'-transition'.length)
    return `属性「${fieldLabel(base)}」变化时的过渡：duration 时长（毫秒），delay 延迟。只对「常量改常量」生效；字段表达式之间不会平滑过渡。`
  }
  return ''
}
